aws:
- account_id: '121169888995'
  account_name: jit bandit
  regions:
  - us-east-1
  type: account
  environment: staging
- account_id: '121169789995'
  account_name: jit bandit
  regions:
  - us-east-1
  type: account
  environment: staging

applications:
- application_name: Jit Platform
  type: web
  url: https://platform.jit.io/
  environment: staging


deployment:
  environments:
  - staging
