aws:
- account_id: '121169888995'
  account_name: jit bandit
  regions:
  - us-east-1
  type: account
- account_id: '121169888000'
  account_name: jit asset jit
  regions:
  - us-east-1
  type: account

deployment:
  environments:
  - staging
