aws:
- account_id: '78787878787'
  account_name: account 1
  regions:
  - us-east-1
  type: account
  environment: staging
- account_id: '1234567899'
  account_name: account 2
  regions:
  - us-east-1
  type: account
  environment: ogogogogogog

applications:
- application_name: Jity
  headers: []
  swagger_file_paths:
  - https://api.jit.io
  type: api
  environment: dsfbgfdgbdfb
- application_name: Jity 2
  type: web
  url: https://platform.jit.io/
  environment: lalalallalalala

deployment:
  environments:
    staging:
      type: non_production
