aws:
- account_id: '78787878787'
  account_name: account 1
  regions:
  - us-east-1
  type: account
  environment: staging
- account_id: '1234567899'
  account_name: account 2
  regions:
  - us-east-1
  type: account
  environment: prod

applications:
- application_name: Jit API
  headers: []
  swagger_file_paths:
  - https://api.jit.io
  type: api
  environment: zczxczxc
- application_name: Jit cascacsac
  headers: []
  swagger_file_paths:
  - https://api.jit.io
  type: api
  environment: acdvf
- application_name: Jit Platform
  type: web
  target_url: https://platform.jit.io/
  authentication: False
  environment: dsavbfb

deployment:
  environments:
  - staging
