aws:
- account_id: '121169888995'
  account_name: jit bandit
  regions:
  - us-east-1
  type: account
  environment: staging
- account_id: '121169789995'
  account_name: jit bandit
  regions:
  - us-east-1
  type: account
  environment: staging


deployment:
  environments:
  - staging
